Fix the ghub-graphql error.
The error was

```
Error: (wrong-type-argument sequencep listp) on code-review-start
```

And it is too cryptic because the code uses deferred.el for github
operations.

The `(setq deferred:debug-on-signal t)` helps to get a better error
and more useful stack trace where we can see the `(void-function
ghub-graphql)` error.

The root cause is that `ghub` package has removed the `ghub-graphql`
and replaced it with `ghub-query`.

For now `ghub` also provides `ghub-legacy` that restores the old
function (and the fix here adds that import).

A better fix is to update the code to use `ghub-query`.

See also:
* https://github.com/magit/ghub/blob/main/CHANGELOG#v500----2025-09-09
* https://github.com/wandersoncferreira/code-review/issues/222.